version: "3.7"

# https://docs.influxdata.com/influxdb/v1.7/administration/config
services:
  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      - influxdb:/var/lib/influxdb
volumes:
  influxdb:
