version: "4"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
      - 8083:8083
      - 8088:8088
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
    restart: "${RESTART}"
    volumes:
      - influxdb-vol:/var/lib/influxdb

volumes:
  influxdb-vol:

