version: "4"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086-8086
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED="true"
     restart: "${RESTART}"
    volumes:
      - influxdb-vol:/var/lib/influxdb
    network_mode: bridge

volumes:
  influxdb-vol:
    driver: local
