version: "4"

services:
  influxdb:
    image: influxdb:1.7.9
    ports:
      - ${INFLUXDB_PORT1}:3306/tcp
      - ${INFLUXDB_PORT2}:3306/tcp
      - ${INFLUXDB_PORT3}:3306/tcp
    environment:
      - INFLUXDB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - INFLUXDB_DATABASE=${MYSQL_DATABASE}
      - INFLUXDB_USER=${MYSQL_USER}
      - INFLUXDB_PASSWORD=${MYSQL_PASSWORD}
     restart: "${RESTART}"
    volumes:
      - influxdb-vol:/var/lib/influxdb
    network_mode: bridge

volumes:
  influxdb-vol:
    driver: local
