version: "4"

  # https://docs.influxdata.com/influxdb/v1.7/administration/configservices:
services:
  influx_db:
    image: influxdb:latest
    ports:
      - 8086:8086
      - 8083:8083
      - 8088:8088
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
    volumes:
      - influxdb-vol:/var/lib/influx_db
    network_mode: bridge
    restart: "${RESTART}"
    
volumes:
  influxdb-vol:
      driver: local
